[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", NPM_VERSION = "9.9.4" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 