[build]
  command = "npm install && npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.9.4"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.cloudflare.com fonts.googleapis.com fonts.gstatic.com; img-src 'self' data: blob: *.cloudflare.com; style-src 'self' 'unsafe-inline' *.cloudflare.com fonts.googleapis.com; font-src 'self' fonts.gstatic.com fonts.googleapis.com; connect-src 'self';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 